spring:
  config:
    activate:
      on-profile: "qa"

cards:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Anshu - QA Lead"
    email: "anshu@gmail.com"
  onCallSupport:
    - 6363
    - 4848
