spring:
  config:
    activate:
      on-profile: "prod"

loans:
  message: "Welcome to Eazybank Loans related prod API's"
  contactDetails:
    name: "Darshan Product Owner"
    email: "darsh@gmail.com"
  onCallSupport:
    - 9090
    - 5454
