spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Anshu - QA Lead"
    email: "anshu@gmail.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345